-d D:\GitHub\FPGA\Tang Nano 20k\Led\Led_flash\impl\gwsynthesis\Led_flash.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst D:\GitHub\FPGA\Tang Nano 20k\Led\Led_flash\src\Led_flash.cst
-cfg D:\GitHub\FPGA\Tang Nano 20k\Led\Led_flash\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
