-d /home/sonny/Documents/GitHub/FPGA/Tang Nano 20k/Button_Press/impl/gwsynthesis/Button_Press.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/sonny/Documents/GitHub/FPGA/Tang Nano 20k/Button_Press/src/Button_Press.cst
-cfg /home/sonny/Documents/GitHub/FPGA/Tang Nano 20k/Button_Press/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
